// Auto-generated by scripts/build-glossary.ts
export type GlossaryEntry = { index: number; title: string; slug: string };
export const glossary: GlossaryEntry[] = [
  {
    "index": 1,
    "title": "Expressive individualism",
    "slug": "expressive-individualism"
  },
  {
    "index": 2,
    "title": "Sexual revolution",
    "slug": "sexual-revolution"
  },
  {
    "index": 3,
    "title": "Social imagery (the social imaginary)",
    "slug": "social-imagery-the-social-imaginary"
  },
  {
    "index": 3,
    "title": "Distrust of the argument from design",
    "slug": "distrust-of-the-argument-from-design"
  },
  {
    "index": 4,
    "title": "Relativity of knowledge",
    "slug": "relativity-of-knowledge"
  },
  {
    "index": 1,
    "title": "The Spirit of God,2",
    "slug": "the-spirit-of-god2"
  },
  {
    "index": 1,
    "title": "They might have come under the wave of some cultural influence from one or more civilizations, which had reached and affected them all alike at dates subsequent to their dispersion",
    "slug": "they-might-have-come-under-the-wave-of-some-cultural-influence-from-one-or-more-civilizations-which-had-reached-and-affected-them-all-alike-at-dates-subsequent-to-their-dispersion"
  },
  {
    "index": 1,
    "title": "the early Muslims who gave preference to verses indicating Divine freedom from any likeness to human beings; the anti",
    "slug": "the-early-muslims-who-gave-preference-to-verses-indicating-divine-freedom-from-any-likeness-to-human-beings-the-anti"
  },
  {
    "index": 2,
    "title": "Relativism of moral and ethical discourse",
    "slug": "relativism-of-moral-and-ethical-discourse"
  },
  {
    "index": 1,
    "title": "It encouraged the careful study of nature, which has come to be known as science, on the supposition that nature reveals her essence by her acts",
    "slug": "it-encouraged-the-careful-study-of-nature-which-has-come-to-be-known-as-science-on-the-supposition-that-nature-reveals-her-essence-by-her-acts"
  },
  {
    "index": 2,
    "title": "It did away with the doctrine of forms imperfectly realized",
    "slug": "it-did-away-with-the-doctrine-of-forms-imperfectly-realized"
  }
];
