import fs from "fs";
import fsp from "fs/promises";
import path from "path";
import mammoth from "mammoth";

type GlossaryEntry = { index: number; title: string; slug: string };

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

async function main() {
  const root = process.cwd();
  const docxPath = path.join(root, "content", "source", "Teaching Glossary.docx");
  const outTs = path.join(root, "shared", "glossary.ts");

  if (!fs.existsSync(docxPath)) {
    console.error("[build:glossary] Missing docx:", docxPath);
    process.exit(1);
  }

  const { value: html } = await mammoth.convertToHtml({ path: docxPath });

  // Extract lines from HTML text; keep only likely numbered headings.
  const text = html
    .replace(/<\/?(p|strong|em|u|span|br|h[1-6])[^>]*>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/\u00A0/g, " ")
    .replace(/\s+\n/g, "\n")
    .replace(/\n+/g, "\n")
    .trim();

  const lines = text.split(/\n/).map((l) => l.trim()).filter(Boolean);

  const entries: GlossaryEntry[] = [];
  const seen = new Set<string>();

  const numberedRe = /^(\d+)[)\.]\s*(.+)$/; // e.g., "1. Agathology" or "1) ..."
  for (const line of lines) {
    const m = line.match(numberedRe);
    if (!m) continue;
    const index = parseInt(m[1], 10);
    const titleRaw = m[2].trim();
    // Stop at first period if it looks like body content
    const title = titleRaw.replace(/\s*[:.-].*$/, "").trim() || titleRaw;
    const slug = slugify(title);
    if (!slug || seen.has(slug)) continue;
    seen.add(slug);
    entries.push({ index, title, slug });
  }

  if (entries.length === 0) {
    console.error("[build:glossary] No entries parsed. Check the DOCX format.");
    process.exit(1);
  }

  const ts = `// Auto-generated by scripts/build-glossary.ts\n` +
    `export type GlossaryEntry = { index: number; title: string; slug: string };\n` +
    `export const glossary: GlossaryEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

  await fsp.writeFile(outTs, ts, "utf-8");
  console.log(`[build:glossary] Wrote ${entries.length} entries to ${outTs}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

