import fs from "fs";
import fsp from "fs/promises";
import path from "path";
import mammoth from "mammoth";

type GlossaryEntry = {
  index: number;
  title: string;
  slug: string;
  bodyHtml: string;
};

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

function plainText(html: string): string {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function cleanBodyHtml(html: string): string {
  return html
    // These are document-level category labels, not part of an entry definition.
    .replace(/<h[1-3][^>]*>[\s\S]*?<\/h[1-3]>/g, "")
    // A small number of body paragraphs are mis-styled as Heading 4 in Word.
    .replace(/<h4[^>]*>/g, "<p>")
    .replace(/<\/h4>/g, "</p>")
    // Word bookmarks are not meaningful in the web glossary and duplicate IDs
    // when all entries are displayed on the same page.
    .replace(/<a id="[^"]*"><\/a>/g, "")
    // Keep footnote reference numbers as readable text without broken links.
    .replace(/<sup><a href="#[^"]*" id="[^"]*">([\s\S]*?)<\/a><\/sup>/g, "<sup>$1</sup>")
    .trim();
}

async function main() {
  const root = process.cwd();
  const docxPath = path.join(root, "content", "source", "Teaching Glossary.docx");
  const outTs = path.join(root, "shared", "glossary.ts");

  if (!fs.existsSync(docxPath)) {
    console.error("[build:glossary] Missing docx:", docxPath);
    process.exit(1);
  }

  const { value: convertedHtml, messages } = await mammoth.convertToHtml({ path: docxPath });
  // Mammoth appends all Word footnote definitions after the document body. They
  // are excluded here because their references remain visible inline and the
  // footnote block does not belong to the final glossary entry.
  const html = convertedHtml.split(/<ol><li id="footnote-1">/i, 1)[0];
  const headingRe = /<h4[^>]*>([\s\S]*?)<\/h4>/gi;
  const headings = [...html.matchAll(headingRe)].filter((match) => {
    const text = plainText(match[1]);
    // Real glossary headings are compact labels. Two long prose paragraphs in
    // the source document accidentally use the same Word heading style.
    return text.length > 0 && text.length <= 160;
  });
  const entries: GlossaryEntry[] = [];
  const seen = new Set<string>();

  for (let i = 0; i < headings.length; i += 1) {
    const match = headings[i];
    const title = plainText(match[1]);
    const slug = slugify(title);
    if (!title || !slug) continue;

    const bodyStart = match.index! + match[0].length;
    const bodyEnd = headings[i + 1]?.index ?? html.length;
    const bodyHtml = cleanBodyHtml(html.slice(bodyStart, bodyEnd));
    if (!bodyHtml) {
      console.warn(`[build:glossary] Empty definition: ${title}`);
    }

    if (seen.has(slug)) {
      const existing = entries.find((entry) => entry.slug === slug)!;
      existing.bodyHtml = [existing.bodyHtml, bodyHtml].filter(Boolean).join("<hr>");
      continue;
    }

    seen.add(slug);
    entries.push({ index: entries.length + 1, title, slug, bodyHtml });
  }

  if (entries.length === 0) {
    console.error("[build:glossary] No Heading 4 entries parsed. Check the DOCX styles.");
    process.exit(1);
  }

  const ts =
    "// Auto-generated by scripts/build-glossary.ts from content/source/Teaching Glossary.docx\n" +
    "export type GlossaryEntry = { index: number; title: string; slug: string; bodyHtml: string };\n" +
    `export const glossary: GlossaryEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

  await fsp.writeFile(outTs, ts, "utf-8");
  console.log(
    `[build:glossary] Wrote ${entries.length} full entries to ${outTs}` +
      (messages.length ? ` (${messages.length} document conversion notices)` : ""),
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
